# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RequestWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(298, 91)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.lblId = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblId.setFont(font)
        self.lblId.setObjectName("lblId")
        self.gridLayout.addWidget(self.lblId, 0, 1, 1, 1)
        self.lblLastRequest = QtWidgets.QLabel(Form)
        self.lblLastRequest.setObjectName("lblLastRequest")
        self.gridLayout.addWidget(self.lblLastRequest, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lblAttemptCount = QtWidgets.QLabel(Form)
        self.lblAttemptCount.setObjectName("lblAttemptCount")
        self.gridLayout.addWidget(self.lblAttemptCount, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.lblStatus = QtWidgets.QLabel(Form)
        self.lblStatus.setObjectName("lblStatus")
        self.gridLayout.addWidget(self.lblStatus, 3, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lblId.setText(_translate("Form", "txtId"))
        self.lblLastRequest.setText(_translate("Form", "TextLabel"))
        self.label.setText(_translate("Form", "id:"))
        self.lblAttemptCount.setText(_translate("Form", "10"))
        self.label_3.setText(_translate("Form", "last request attempt:"))
        self.label_5.setText(_translate("Form", "attempt count"))
        self.label_7.setText(_translate("Form", "status"))
        self.lblStatus.setText(_translate("Form", "open"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
